
modLoader="kotlinforforge"
loaderVersion="[1,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="wiedzminstvo"
version="${file.jarVersion}"
displayName="Wiedźmiństwo"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="logo.png"
# credits="none - yet" #optional
authors="Lai0n, TOTAL Lummox"
description='''
*dramatic music comes on*
Become a witcher on the path, fighting, exploring. In world full of possibili-
*record scratching*

Nah, we just like witcher world and since there is no other more complete mod, we've decided
to create our own. We promise nothing, but our aim is to bring monsters, alchemy, contracts
and some more stuff to the game. We work on this mod actively yet perhaps vaguely as we don't
have much free time in our personal life.

That's about it. Please enjoy our mod and if you wan't to help out, feel free to join our discord
server or contribute on github repository :)
'''
[[dependencies.wiedzminstvo]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wiedzminstvo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
